### ISSUE TITLE
Boss gain bot command

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#74] opened 2021-03-05 05:01 UTC
I think it would be cool to see **just the bosses** that have been worked on in a period :)

-Individual lookup: `!gained --bosses` or `!bosses gained` would bring up the same thing as doing `!gained`, but all XP/minigames would be excluded.

-Group lookup: `!group gained bosses` would bring up the group's overall EHB for the period, as well as the total KC for each boss that had "gains" in that period (sorted biggest gain to smallest gain). For example:

**Group name: XXXXX**
**1 Week Boss Gains**
- EHB: XXX
1. Vorkath: 520
2. COX: 100
3. Venenatis: 10

These filters/metrics could potentially be expanded to XP/activities as well

**Comment by psikoi** [comment] 2021-03-05 10:20
For the individual gains, this is a duplicate of https://github.com/wise-old-man/discord-bot/issues/48

As for group gains, this can't really be done as the bot would have to send 44 different API requests (one for each boss) to be able to build that list. This is likely too big a price to pay for a command.

**Closed by psikoi** 2021-03-05 10:20 UTC
